
version: '3.9'
services:
  app:
    image: nodejs2023q2-service-app
    container_name: app
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src/


    networks:
      - custom_network  
      
  postgres:
    image: nodejs2023q2-service-db
    container_name: postgres
    build: ./src/db
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: ["postgres", "-c", "logging_collector=true", "-c", "log_directory=/var/log/postgresql"]  
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pglogs:/var/log/postgresql
    networks:
      - custom_network

volumes:
  pgdata: 
  pglogs: 

networks:
  custom_network:
    driver: ${DRIVER}
