version: '3.9'
services:

  app:
    container_name: app
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}

  database:
    container_name: postgres
    build: ./src/db
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

